FORMAT: 1A
HOST: http://localhost:3000

# VUTTR

    Simples API para gerenciamento de ferramentas úteis para desenvolvedores.

# Group Tools

    Rotas relacionadas ao gerenciamento das ferramentas na API.

## Listar e cadastar itens [/tools]

### Listar todos os itens [GET]
+ Response 200 (application/json)
    + Attributes (array[ToolId])

### Cadastrar um novo item [POST]
+ Request (application/json)
    + Attributes (Tool)

+ Response 201 (application/json)
    + Attributes (ToolId)

## Buscar item por tag [/tools?tag={tag}]
    Permite filtar os itens de acordo com uma tag especifica.

### Lista os itens por tag [GET]
+ Parameters
    + tag: php (string) - Sendo "tag" a tag que será aplicada no filtro.

+ Response 200 (application/json)
    + Attributes (array[ToolId]) 

## Deletar um item [/tools/{id}]
+ Parameters
    + id: 12 (number) - ID da ferramenta que será deletada.

### Deletar um item por ID [DELETE]
+ Response 200

            {}


# Data Structures

## Tool (object)

+ title : Laravel (string) - Titulo da ferramenta
+ link : https://laravel.com/ (string) - Link web da ferramenta
+ description : Framework PHP para desenvolvimento de sites e aplicações para web (string) - Descrição da ferramenta
+ tags: php , framework, web, fullstack (array[string])

## ToolId (object)

+ id (number) - ID da ferramenta
+ title : Laravel Framework (string) - Titulo da ferramenta
+ link : https://laravel.com/ (string) - Link web da ferramenta
+ description : Framework PHP para desenvolvimento de sites e aplicações para web (string) - Descrição da ferramenta
+ tags: php , framework, web, fullstack (array[string])
