FORMAT: 1A
HOST: http://localhost:3000

FORMAT: 1A

# VUTTR

    Simples API para gerenciamento de ferramentas úteis para desenvolvedores.

# Group Ferramentas

    Rotas relacioadas a Ferramentas na API.

## Coleção Ferramentas [/tools]

### Listar todas as Ferramentas [GET]
+ Response 200 (application/json)
    + Attributes (array[ToolId])

### Cadastrar uma nova Ferramenta [POST]
+ Request (application/json)
    + Attributes (Tool)

+ Response 201 (application/json)
    + Attributes (ToolId)

## Busca por tag [/tools?tag={tag}]
    Permite filtar as ferramentas de acordo com uma tag especifica

### Lista as Ferramentas por tag [GET]
+ Parameters
    + tag: php (string) - Tag que será Aplidada no filtro.

+ Response 200 (application/json)
    + Attributes (array[ToolId]) 

## Deletar Ferramenta [/tools/{id}]
+ Parameters
    + id: 12 (number) - ID da ferramenta que será deletada

### Deletar [DELETE]
+ Response 200

            {}


# Data Structures

## Tool (object)

+ title : Laravel Framework (string) - Titulo da ferramenta
+ link : https://laravel.com/ (string) - Link web da ferramenta
+ description : Framework PHP para desenvolvimento de sites e aplicações para web (string) - Descrição da ferramenta
+ tags: php , framework, web, fullstack (array[string])

## ToolId (object)

+ id (number) - ID da ferramenta
+ title : Laravel Framework (string) - Titulo da ferramenta
+ link : https://laravel.com/ (string) - Link web da ferramenta
+ description : Framework PHP para desenvolvimento de sites e aplicações para web (string) - Descrição da ferramenta
+ tags: php , framework, web, fullstack (array[string])
